### ISSUE TITLE
`OpenMP.Parallel.Critical` is Inefficient

### ISSUE THREAD

**Issue by computablee** [computablee/OpenMP.NET#2]
The method `OpenMP.Parallel.Critical` located [here](https://github.com/computablee/OpenMP.NET/blob/1b86469349f3d8e608534b3df619f70b0057238b/OpenMP.NET/Parallel.cs#L53) is inefficient. There is a single static lock in the `OpenMP.Parallel` class. Consider the following OpenMP:
```c
#pragma omp parallel
{
    #pragma omp critical
    {
        critical_func_1();
    }
    #pragma omp critical
    {
        critical_func_2();
    }
}
```
In this code, there are two critical regions within the parallel region, and one thread can be executing `critical_func_1` while a second can be executing `critical_func_2`. In OpenMP.NET, this is not possible because all critical regions use a single, shared lock. Improvements to this would be appreciated.

**Comment by diogolopes18-cyber** [comment]
Repo seems cool, and the work you develop is pretty interesting. Would definitely like to help! My experience is mainly with ASP.NET and EF Core, however I've worked with embedded systems (C and Python) in the past

**Comment by diogolopes18-cyber** [comment]
Yeah, I'm pretty sure I would just need to figure out a way to cleverly use the `locks`. Will brainstorm throughout the week and share my thoughts with you. Thanks!

**Comment by computablee** [comment]
@diogolopes18-cyber If we can't get it looking like the C code sample earlier, it should be fine to create instances of a `OpenMP.Critical` class, like so:
```cs
OpenMP.Critical critical1 = new OpenMP.Critical();
OpenMP.Critical critical2 = new OpenMP.Critical();
critical1.Critical(() => {
    critical_func_1();
});
critical2.Critical(() => {
    critical_func_2();
});
```

**Comment by computablee** [comment]
Removed "good first issue" since this appears to be a harder problem than it appeared on the surface. Brainstorming with some colleagues.

**Comment by computablee** [comment]
Closing this issue with a push. Figured out you can use the `Action` as a key to a `Dictionary`, and as the values store objects for locks. See https://github.com/computablee/OpenMP.NET/blob/main/OpenMP.NET/Parallel.cs#L86
