### ISSUE TITLE
Modifications to `OpenMP.Parallel.For`

### ISSUE THREAD

**Issue by computablee** [computablee/OpenMP.NET#4]
This is a pretty big change, and wouldn't recommend it as a first commit. The changes requested are threefold:

1. Add `OpenMP.Parallel.Parallel` to create a parallel region containing code that can be executed by a team of threads. This should be roughly the same as `#pragma omp parallel`
2. Change `OpenMP.Parallel.For` to act like `#pragma omp for`, not `#pragma omp parallel for`
3. Add `OpenMP.Parallel.ParallelFor`. This should be a wrapper around the previous two methods mentioned in 1 and 2.

Once we get a PR with this going through, we'll look at incorporating stuff like `#pragma omp single` and `#pragma omp master`.

**Comment by jotasprout** [comment]
Yeah, I am definitely eager to use this to sharpen my new C# (no pun intended) and .NET skills so I'm going to start looking at it but if anyone who can do it faster should be chosen before me.

**Comment by computablee** [comment]
@jotasprout I won't assign you to this quite yet, but if you want to make some incremental PRs we can see how things are looking. I might have some time to work on this myself this weekend.

**Comment by computablee** [comment]
Okay, fall break has come and I'm getting a break from grad school. Assigning myself to this issue, hopefully have something today.

**Comment by computablee** [comment]
Done. Not as well-tested as I'd like, but the few unit tests I have seem to indicate things are working properly.
